M48
; DRILL file {KiCad 7.0.10} date Monday, March 04, 2024 at 12:58:28 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-04T12:58:28-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.000
%
G90
G05
T1
X139.502Y-96.266
T2
X106.172Y-96.266
M30
